# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

paginate:         5

# setup
title:            RoboEagles
tagline:          'Tagline'
description:      'FRC Team 3081'
url:              http://kennedyrobotics.com
baseurl:          /
version:          1.0
timezone:         America/Chicago

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

- jekyll-feed