# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

paginate:         5
# setup
title:            Title
tagline:          'Tagline'
description:      'desc'
url:              http://kennedyrobotics.com
baseurl:          /


gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

- jekyll-feed